// ─────────────────────────────────────────────
// UPLOAD MODULE
//
// Flow:
//   1. User clicks "+ Upload" in nav
//   2. Picks image from device (or drag & drop)
//   3. FileReader converts file → base64
//   4. POST /images/upload { base64_image, name, topic, hashtags }
//   5. BE generates image_id → uploads to S3 → saves DB record
//   6. Response: { id, s3url, name, topic, hashtags, postedBy, timestamp }
//   7. Grid refreshes — new image appears instantly
// ─────────────────────────────────────────────

const Upload = (() => {

  let selectedBase64 = null   // "data:image/jpeg;base64,/9j/..."
  let selectedFile   = null   // original File object (for size/type info)

  // ── OPEN MODAL ────────────────────────────
  function open() {
    if (!Auth.isLoggedIn()) {
      Auth.openModal('login')
      UI.toast('Sign in to upload wallpapers')
      return
    }
    clearForm()
    document.getElementById('uploadModal').classList.add('open')
  }

  // ── FILE PICKED ───────────────────────────
  // Called when user picks file OR drops file on the zone
  function onFilePicked(input) {
    const file = input.files && input.files[0]
    if (!file) return

    // Validate type
    if (!file.type.startsWith('image/')) {
      UI.toast('Please pick an image file (JPG, PNG, WEBP)')
      return
    }

    // Validate size — 5MB max
    if (file.size > 5 * 1024 * 1024) {
      UI.toast('Image too large — max 5MB allowed')
      return
    }

    selectedFile = file

    // Show file info below preview
    const sizeKB = (file.size / 1024).toFixed(0)
    document.getElementById('upFileInfo').textContent =
      `${file.name} · ${sizeKB} KB · ${file.type.split('/')[1].toUpperCase()}`
    document.getElementById('upFileInfo').style.display = 'block'

    // Auto-fill name from filename (strip extension, clean dashes)
    const nameInput = document.getElementById('upName')
    if (!nameInput.value) {
      nameInput.value = file.name
        .replace(/\.[^.]+$/, '')
        .replace(/[-_]/g, ' ')
        .replace(/\b\w/g, c => c.toUpperCase())  // Title Case
    }

    // Convert file to base64 via FileReader
    const reader = new FileReader()
    reader.onload = (e) => {
      selectedBase64 = e.target.result   // full data URL
      showPreview(selectedBase64)
    }
    reader.onerror = () => {
      UI.toast('Could not read file — try again')
    }
    reader.readAsDataURL(file)  // triggers onload with base64 result
  }

  // ── SHOW IMAGE PREVIEW ────────────────────
  function showPreview(src) {
    const img      = document.getElementById('uploadPreviewImg')
    const placeholder = document.getElementById('uploadPreviewText')
    img.src              = src
    img.style.display    = 'block'
    placeholder.style.display = 'none'
  }

  // ── SUBMIT ────────────────────────────────
  // POST /images/upload
  // Body : { base64_image, name, topic, hashtags[] }
  // Token: Authorization: Bearer <token>  ← injected by http() in api.js
  //
  // Response: { id, s3url, name, topic, postedBy, hashtags, timestamp }
  //   id     = UUID generated by BE — same as S3 folder name
  //   s3url  = full public S3 URL of the uploaded image
  async function submit() {
    const name    = document.getElementById('upName').value.trim()
    const topic   = document.getElementById('upTopic').value.trim().toLowerCase()
    const hashRaw = document.getElementById('upHashtags').value.trim()
    const errEl   = document.getElementById('upErr')
    const btn     = document.getElementById('upBtn')
    const bar     = document.getElementById('upProgressBar')
    const prog    = document.getElementById('upProgress')

    errEl.textContent = ''

    // ── Validate ──
    if (!selectedBase64) { errEl.textContent = 'Please pick an image first'; return }
    if (!name)           { errEl.textContent = 'Name is required';           return }
    if (!topic)          { errEl.textContent = 'Topic is required';          return }

    // Parse hashtags — split by comma, strip # prefix, remove empty
    const hashtags = hashRaw
      ? hashRaw.split(',').map(h => h.trim().replace(/^#/, '')).filter(Boolean)
      : []

    // ── Show progress UI ──
    btn.textContent   = 'Uploading to S3…'
    btn.disabled      = true
    bar.style.display = 'block'
    animateProgress(prog, 0, 60, 800)   // animate 0 → 60% while waiting

    try {
      // ── POST /images/upload ──
      const data = await http('/images/upload', {
        method: 'POST',
        body: JSON.stringify({
          base64_image: selectedBase64,  // "data:image/jpeg;base64,..."
          name,
          topic: topic.toLowerCase(),
          hashtags,
        })
      })

      // Animate progress to 100%
      animateProgress(prog, 60, 100, 400)

      setTimeout(() => {
        // Close modal, reset form
        document.getElementById('uploadModal').classList.remove('open')
        clearForm()

        // Show success with image name and generated id
        UI.toast(`"${data.name}" uploaded! ID: ${data.id.slice(0, 8)}…`)

        // Reload grid so new image appears
        Images.load()
      }, 500)

    } catch (e) {
      errEl.textContent = e.message
      bar.style.display = 'none'
      prog.style.width  = '0%'
    } finally {
      btn.textContent = 'Upload to S3'
      btn.disabled    = false
    }
  }

  // ── PROGRESS BAR ANIMATION ────────────────
  function animateProgress(el, from, to, duration) {
    const start     = performance.now()
    const diff      = to - from
    function step(now) {
      const elapsed = Math.min((now - start) / duration, 1)
      el.style.width = (from + diff * elapsed) + '%'
      if (elapsed < 1) requestAnimationFrame(step)
    }
    requestAnimationFrame(step)
  }

  // ── CLEAR FORM ────────────────────────────
  function clearForm() {
    selectedBase64 = null
    selectedFile   = null

    document.getElementById('upName').value      = ''
    document.getElementById('upTopic').value     = ''
    document.getElementById('upHashtags').value  = ''
    document.getElementById('upErr').textContent = ''
    document.getElementById('upFileInput').value = ''
    document.getElementById('upFileInfo').style.display = 'none'
    document.getElementById('upFileInfo').textContent   = ''
    document.getElementById('upProgress').style.width   = '0%'
    document.getElementById('upProgressBar').style.display = 'none'

    // Reset preview
    const img  = document.getElementById('uploadPreviewImg')
    const text = document.getElementById('uploadPreviewText')
    img.src = ''; img.style.display = 'none'
    text.style.display = ''
  }

  return { open, onFilePicked, submit }
})()